### ISSUE TITLE
OS_PASSWORD read

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#101]
Newer versions of openstack use the following code in the openrc.sh file

echo "Please enter your OpenStack Password: "
read -sr OS_PASSWORD_INPUT
export OS_PASSWORD=$OS_PASSWORD_INPUT

It would be good if we besides placing the password in the yaml file have some mechanism to ask for a field when a specific value is set. Best would be if we test if the OS_Password has this value and if it has we ask, than we set it to the value. so its preseved. However this may not work as this is done independent for the shelll. So we need to execute some optional source that we create or have a command that does the password interactively via the above lines and we call it somehow.
we also need to unset it.

work with gregor on this

**Comment by laszewsk** [comment]
this is implemented for comet and can easily be modified to work with others

**Comment by gouravshenoy** [comment]
Implemented for OpenStack Cloud Provider.

Cloudmesh.yaml file changes:
```yaml
OS_PASSWORD: readline
```

Output:
```cmd
PS C:\Users\Gaurav-PC> cm

+=======================================================+
.   ____ _                 _                     _      .
.  / ___| | ___  _   _  __| |_ __ ___   ___  ___| |__   .
. | |   | |/ _ \| | | |/ _` | '_ ` _ \ / _ \/ __| '_ \  .
. | |___| | (_) | |_| | (_| | | | | | |  __/\__ \ | | | .
.  \____|_|\___/ \__,_|\__,_|_| |_| |_|\___||___/_| |_| .
+=======================================================+
                     Cloudmesh Shell

cm> image refresh --cloud juno
Password:
Refresh image for cloud juno. ok.
```

**Comment by gouravshenoy** [comment]
Closing this issue now.

**Comment by laszewsk** [comment]
could you create a new issue. IN comet we introduced the concept of a logon, we may want to do he same for cloud commands

so maybe we can create a new logon command

cloud logon CLOUDNAME

this woudl than store  “in memory” the password for the cloud


lets assume we also have the concept of an active cloud (see command cloud from old cloudmesh, also i think drafted here than we can do )


cloud logon 

	logs us on on all active clouds ( we could start with clouds which we put an active into defaults). iT would also activate the clouds
	if password is readline or read, than we use the python get pass command to read the password.

cloud logon CLOUDNAME

	logs in to a named cloud. It would also activate the cloud

cloud list 

	lists the status of a cloud e.g. if its active or not

cloud activate CLOUDNAME
cloud activate all
cloud deactivate CLOUDNAME

allows to selectivee ly activate the clouds. NOte that the password is still in memory an that activating and deactiavting is quick

cloud logout CLOUDNAME

	removes the password from memory
