### ISSUE TITLE
wrong usage of SQL

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#102]
The one place we can call sql is in the db directory, everything else must be using from there only from CLoudmeshDatabase. THus the only thing that is allowed to be imported is CloudmeshDatabase 

Below find a tentative list of correct and incorrect usages.

Task 1: verify if the list is ok
Task 2: go through each item and fix
Task 3: if we need other methods, they can be implemented

Please remember that internal sql object MSUT NOT be exported or used outside CloudmeshDatabase.

Allowed usage:
* [x] ./cloudmesh_client/db/CloudmeshDatabase.py:from cloudmesh_client.db.model import database, table, tablenames, \
* [x] ./cloudmesh_client/db/model.py:    TODO: An import to the model.py will instantiate the db object.
* [x] ./cloudmesh_client/db/SSHKeyDBManager.py:from cloudmesh_client.db.model import KEY
* [x] ./cloudmesh_client/db/__init__.py:from cloudmesh_client.db.model import tables, tablenames, table, 
database

Bugs
* [x] ./cloudmesh_client/__init__.py:from cloudmesh_client.db.model import DEFAULT
* [x] ./cloudmesh_client/__init__.py:from cloudmesh_client.db.model import KEY
* [x] ./cloudmesh_client/__init__.py:from cloudmesh_client.db.model import tables
* [x] ./cloudmesh_client/__init__.py:from cloudmesh_client.db.model import tablenames
* [x] ./cloudmesh_client/cloud/default.py:from cloudmesh_client.db import model
* [x] ./cloudmesh_client/cloud/flavor.py:from cloudmesh_client.db import model
* [x] ./cloudmesh_client/cloud/group.py:from cloudmesh_client.db import model
* [x]  ./cloudmesh_client/cloud/image.py:from cloudmesh_client.db import model
* [x] ./cloudmesh_client/cloud/list.py:from cloudmesh_client.db import model
* [x] ./cloudmesh_client/cloud/reservation.py:from cloudmesh_client.db.model import RESERVATION
* [x] ./cloudmesh_client/cloud/secgroup.py:from cloudmesh_client.db import model
* [x] ./cloudmesh_client/db/__init__.py:from cloudmesh_client.db.model import DEFAULT, KEY, RESERVATION, GROUP

**Comment by vaglomangirish** [comment]
Fixed reservation.py to remove the db model import and added some more code to cloudmesh database to pass db arguments dynamically.

**Comment by gouravshenoy** [comment]
Fixed group.py and removed db model imports.

**Comment by ehdsouza** [comment]
Fixed default and image.py, and removed db model import

**Comment by gouravshenoy** [comment]
Fixed secgroup.py and removed db model imports.

**Comment by gouravshenoy** [comment]
Fixed all import references to db.model in all classes. Marking this issue as closed.
