### ISSUE TITLE
Revisit and refactor vm command code to sync and store vm data in database

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#103]
Currently the vm command is configured to communicate only with the cloud and there is no db interaction. Goal is to make it similar to other artifact commands like images wherein it stores and lists data from db and not directly from cloud.

* [x] Add code to store vm data in db.
* [x] Add 'refresh' functionality to sync data from the cloud.

**Comment by vaglomangirish** [comment]
Refresh functionality added

**Comment by vaglomangirish** [comment]
Revised and refactored the VM command code to add the data to db.
Added boot, start, stop functionality.

**Comment by laszewsk** [comment]
The vm data is not properly populated into the database

**Comment by vaglomangirish** [comment]
Checked in code to sync most of the details retrieved from openstack onto the db. What still remains to be addressed are following:-
* [ ] Store IP Addresses
* [ ] Store Volumes Attached
* [ ] Store Security Groups
* [ ] Implement listing of details for specific VM
* [ ] Modify the list order as required.

Currently working on all above...
*

**Comment by vaglomangirish** [comment]
Modified list_vm logic in CloudProviderOpenstackAPI to return a dict with simple keys added for static and floating ips.
This is currently tested for juno. It needs to be tested for chameleon and kilo as well...

**Comment by vaglomangirish** [comment]
Delivered code to include security groups to the data for DB during vm refresh.

**Comment by vaglomangirish** [comment]
Further changes to be done based on discussion in today's meeting:-

* [ ] Implement auto naming scheme based in username for vms (username001, username 002, username 003...)
* [ ] Implement vm default command
* [ ] Implement vm status command
* [ ] Maintain VM login username in the DB
* [ ] Get key attribute from defaults for vm login

**Comment by vaglomangirish** [comment]
Implemented the vm commands as per the requirements.
