### ISSUE TITLE
[client] Cloud Logon Command

### ISSUE THREAD

**Issue by gouravshenoy** [cloudmesh/client#109]
Create a new logon command:
```cmd
cloud logon CLOUDNAME
```
This would then store “in memory” the password for the cloud. Lets assume we also have the concept of an active cloud. 

```cmd
cloud logon
```
This command logs us on all active clouds (we could start with clouds which we put an active into defaults). It would also activate the clouds if password is "readline" or "read", than we use the python get pass command to read the password.

```cmd
cloud logon CLOUDNAME
```
This command logs in to a named cloud. It would also activate the cloud.

```cmd
cloud list 
```
This command lists the status of a cloud e.g. if its active or not.

```cmd
cloud activate CLOUDNAME
cloud activate all
cloud deactivate CLOUDNAME
```
Commands allow to selectively activate the clouds. Note that the password is still in memory an that activating and deactivating is quick.

```cmd
cloud logout CLOUDNAME
```
This command removes the password from memory.

**Comment by gouravshenoy** [comment]
Implemented ```cloud logon``` command. Performs the following:
```cmd
cloud logon CLOUD
cloud logout CLOUD
cloud activate CLOUD
cloud deactivate CLOUD
cloud [--cloud=CLOUD] list
```

**Comment by gouravshenoy** [comment]
Closing this issue.

**Comment by laszewsk** [comment]
I like to review this new feature as important. I also like to identify if there is smoehow a mechanism to use in addition to this ssh keys
