### ISSUE TITLE
Command: vm: manage vms

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#11]
Add the vm command that uses a Provider abstraction. 

* [x] split up tasks between the two of you. For example one can focus on Provider, the other on the command line while assuming the Provider has been implemented. An initial provider could be designed, that just does prints. You update than nosetests ones the provider is finished. 

* [x] implement a OpenstackCloudProvider (we actually have already one, but we may want to do a new one using partial exisithon python api instead of using rest, we may want to file separate issue on this. Work closely with Gregor on this, so that we do the right thing. This is possibly the single most difficult task of this project as we have an existing provider, but want to redesign. There may be issues in that API, as we also need to get quota, limits and other "unusual" information that may not be well documented. IN the past we also found the the REST interface we have works, while the API python interface from openstack does not. we need to figure this out and use what works.
* [x] It looks first up the type of the cloud in the cloudmesh.yaml file and than loads the provider 
* [x] integrate defaults
* [x] integrate groups
* [x] integrate keys
* [x] write nose tests
* [x] update docopt where needed
* [x] create nice examples

**Comment by vaglomangirish** [comment]
Currently we aren't able to integrate keys as the key command code is tuned to add public keys (.pub) and not private keys. We need private key reference to login to VM.

This needs more work on refactoring key command to add private keys too.

Currently the VM command accepts complete path to the private key to login to VM.

**Comment by laszewsk** [comment]
Naturally private keys must NOT be uploaded to the data base. instead, the filename that is associated with the public key may help in location the private key 

Naturally this will than work as we assume the public and the private key are in the same directory.

Also the only thing that needs to be done is to register the public key in the VM. Maybe I misunderstand something.

**Comment by laszewsk** [comment]
See also the documentation at 
http://cloudmesh.github.io/introduction_to_cloud_computing/class/lesson/iaas/openstack.html

**Comment by fugangwang** [comment]
Seems a misunderstanding of what is included in task 'integrate keys'. I think that simply means keypair management for openstack. It should not dealing with the content of the private key file as Gregor mentioned. It's alright to have the private key path specified in VM command to login to VMs. In fact even if the private key is also manged by cloudmesh, in case of passphrase protection (which is always suggested as a good practice of security), user intervention is still needed anyway.

**Comment by vaglomangirish** [comment]
Thanks Prof. Gregor and Fu Gang for your comments and clarifications.
Sorry if my comment was unclear or confusing...
My understanding was that the key database would store all the keys, including private keys and the vm command's --key argument should be provided with the 'database name' of the key and may not be complete path.

Currently following is how it works:-
1) vm start command accepts 'keypair_name' argument that expects a openstack nova keypair name for VM creation.
2) vm login command's --key argument takes the complete path to the private key of the keypair.

Please let me know if this serves the purpose or requires any change in implementation.

**Comment by laszewsk** [comment]
is this completed?
