### ISSUE TITLE
cloudmesh.db

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#117]
When the cloudmesh.db is created its created with the wrong permissions.

it should be 

u+rw
go-rwx

**Comment by laszewsk** [comment]
this also impact windows where file permissions may be differently handeld

**Comment by gouravshenoy** [comment]
Cloudmesh.db file has the right permissions. Verified that cloudmesh.db has ```cmd rw``` for user and no permissions for group/others.
