### ISSUE TITLE
Init: register india

### ISSUE THREAD

**Issue by dasilvad** [cloudmesh/client#12]
cm register india

dir clouds is not being created in ~/.cloudmesh.
what if ~/.cloudmesh dir is not there?

**Comment by laszewsk** [comment]
you need to create …

Shell.mkdir(“~/.cloudmesh”)

**Comment by ehdsouza** [comment]
Checked in code: https://github.com/cloudmesh/client/commit/aacc8860973d9b6d3928b21f0f610a5f3d910532

Directories are now created if not present.
