### ISSUE TITLE
Bug: network

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#126]
pycharm reporst unresolved issue
            result = Network.unreserve_fixed_ip(cloudname=cloudname,
                                                fixed_ip_addr=fixed_ip)

**Comment by gouravshenoy** [comment]
Delivered fix with commit on 12/08/2015 (fix: dev: pycharm inspect error). 
Pycharm does not report any inspect error for NetworkCommand,py. Closing this issue.
