### ISSUE TITLE
Bug: network

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#127]
pycharm shows thsi still has an error and non matching parameters.

            vm_id = cloud_provider.boot_vm(kwargs["name"],
                                           kwargs["image"],
                                           kwargs["flavor"],
                                           key=kwargs["key_name"],
                                           secgroup=kwargs["secgroup_list"],
                                           nics=nics)

**Comment by gouravshenoy** [comment]
Delivered fix with commit on 12//08/2015. Pycharm does not report inspect error now. Closing this issue.
