### ISSUE TITLE
command: group: does not show name of vm

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#135]
when we say group list we want to actually see more the name than the uuid. uuid should be shown only if we do some --all flag or so. We want to make this consistent with other stuff where we favour the vm name and not the uuid.

cm group list
+---------+--------------------------------------+----------+-------+------+
| name    | value                                | user     | cloud | type |
+---------+--------------------------------------+----------+-------+------+
| default | 4a7c... | <username> | kilo  | vm   |
+---------+--------------------------------------+----------+-------+------+

**Comment by gouravshenoy** [comment]
Fixed this issue. Now ```group list``` displays the name of the VM instead of it's id. 
```
$ cm group list
+---------+--------------+----------+-------+------+
| name    | value        | user     | cloud | type |
+---------+--------------+----------+-------+------+
| default | goshenoy-001 | goshenoy | kilo  | vm   |
+---------+--------------+----------+-------+------+
```
