### ISSUE TITLE
tests: cleanup tests so they pass

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#136]
Tests
* [x] Gregor, tests/test_cloud_model.py F
* [x] Gregor, tests/test_hpc.py .FF
* [x] Mangirish, tests/test_keys.py FFF.........FFFF (fixed by Gregor)
* [x] Mangirish, tests/test_register.py F..FF...FFFFFFF (fixed by Gregor)
* [x] Mangirish, tests/test_vm.py F....FF (verified by Gourav)
* [x] Gourav, tests/test_nova.py FFFF (fixed by Gregor)
* [x] Gourav, tests/test_quota.py .FF (fixed by Gregor)
* [x] Gourav, tests/test_secgroup.py FFFFFFF (fixed by Gregor)
* [x] Gourav, tests/test_usage.py F (fixed by Gregor)

**Comment by laszewsk** [comment]
switched hpc test to use comet, however better would be to add a running job

**Comment by gouravshenoy** [comment]
Verified all test cases are passing.
