### ISSUE TITLE
Command: key

### ISSUE THREAD

**Issue by paulo-chagas** [cloudmesh/client#14]
* [x] cm key list
* [x] cm key list --source=db/ cloumesh/ ssh/ git (working towards --source=~/.cloudmesh/cloudmesh.db) - with all formats enabled (json, yaml. table)
* [x] cm key add [--name=name] filename
* [x] cm key get name
* [x] cm key delete name
* [x] Add nosetests for key commands
* [x] cm key list --source=ssh --dir= --> takes key from ~/.ssh inspite of providing the custom path.
* [x] cm key delete --all -> to be implemented at model level
* [x] cm key add --git -> still not working as expected
* [x] cm key delete --select
* [x] cm key default [KEYNAME | --select]
* [x] remove mongo dependency

When I try to print the data from the KEY table like 'cm key list --source=mongo' the table isn't being printed correctly. I don't know why, maybe the object  isn't being converted do dict correctly.

**Comment by vaglomangirish** [comment]
Since we aren't using mongo db for cloudmesh, I am not sure if the comment is valid.

I understand that this task has a broader scope, not just restricted to --source=mongo issue.

Nonetheless, I found that the code does not handle --source=mongo. I added a dummy code to handle it and managed to get this output:-

(ENV)[mangirish@MangoLap client]$ cm key list --source=mongo
{'--all': False,
 '--dir': '~/.ssh',
 '--format': 'table',
 '--git': False,
 '--help': False,
 '--path': '~/.ssh/id_rsa.pub',
 '--select': False,
 '--source': 'mongo',
 '--ssh': False,
 '--username': 'none',
 '-f': False,
 '-h': False,
 'KEYNAME': None,
 'NAME': None,
 'add': False,
 'default': False,
 'delete': False,
 'get': False,
 'list': True}
+------+-----------------+-----------------------------+-------------------------------------------------+--------+
| name | comment         | uri                         | fingerprint                                     | source |
+------+-----------------+-----------------------------+-------------------------------------------------+--------+
|      | dummy mongo key | https://mongo.com/user.keys | 2d:18:a8:03:dd:e1:7e:fe:b3:fa:wr:49:c7:c4:cf:09 |        |
+------+-----------------+-----------------------------+-------------------------------------------------+--------+
(ENV)[mangirish@MangoLap client]$

**Comment by laszewsk** [comment]
as we switched to sqllite, i suggest to change to 

—source=db

and than use ~/.cloudmesh/cloudmesh.db

also may be nice to say

—source=~/.cloudmesh/cloudmesh.db

so you specify a direct path if you do not use the default

**Comment by vaglomangirish** [comment]
I managed to get the following commands working:-

 cm key list
 cm key list --source=db/ cloumesh/ ssh/ git   (working towards --source=~/.cloudmesh/cloudmesh.db) - with all formats enabled (json, yaml. table)
 cm key add [--name=name] filename
 cm key get name
 cm key delete name

Also, I have added nosetests for key command to cover most of the cases that I could think of.

Some issues that I am still working on:-

1) cm key list --source=ssh --dir=<value> --> takes key from ~/.ssh inspite of providing the custom path.
2) cm key delete --all -> to be implemented at model level
3) cm key add --git -> still not working as expected
4) cm key delete --select -> haven't understood the select option well

**Comment by vaglomangirish** [comment]
Currently stuck on getting the github authentication working fine for  cm key add --git.
The basic auth works fine, however the subsequent call to add the key still fails with 401 Unauthorized.
Code snippet:-

sshkey = SSHkey(file_path)
        git_url = "https://api.github.com"
        # Basic Authenticate with git
        print("Authenticating with username = {:} password = {:}".format(username, password))
        r = requests.get("{:}/user".format(git_url), auth=(username, password))
        print("Return code: {:}".format(r.text))
        if (r.status_code == 200):
            print("Git auth success")
            payload = {
                "title": gitkeyname,
                "key": sshkey
            }
            r = requests.post("{:}/user/keys".format(git_url), data = payload, auth=(username, password)) <<--- FAILING AT THIS CALL
            print("Response after post: {:}".format(r.text))
        else:
            raise Exception("Git Authentication Failed")


I am investigating further on getting this to work, though any pointers would be helpful...

Thanks.

**Comment by vaglomangirish** [comment]
Please note that the print statements in the snippet are for debug purpose only and will be removed while delivering the code.

**Comment by vaglomangirish** [comment]
As discussed, changed the Datetime attribute in DB Model to data type string to get rid of serialization error for Datetime type with normal json.dumps, thus removing the pymongo dependency.

**Comment by laszewsk** [comment]
file bug and move on, github we only need to read.

**Comment by vaglomangirish** [comment]
Filed Bug #51 for adding key to git work.

**Comment by vaglomangirish** [comment]
Got the cm key delete --select working, though I found a problem with it:-

(ENV)[mangirish@MangoLap client]$ cm key delete --select
{'--all': False,
 '--dir': '~/.ssh',
 '--format': 'table',
 '--git': False,
 '--help': False,
 '--name': None,
 '--select': True,
 '--source': 'db',
 '--ssh': False,
 '--username': 'none',
 '-f': False,
 '-h': False,
 'FILENAME': None,
 'KEYNAME': None,
 'NAME': None,
 'add': False,
 'default': False,
 'delete': True,
 'get': False,
 'list': False}
delete
('i:', 1)
('i:', 2)
('i:', 3)

KEYS
\\====

    1 - aaaa: 4e:fc:e8:03:4e:c7:8e:ca:30:1a:54:43:8d:24:90:39
    2 - bbbb: 4e:fc:e8:03:4e:c7:8e:ca:30:1a:54:43:8d:24:90:39
    3 - cccc: 4e:fc:e8:03:4e:c7:8e:ca:30:1a:54:43:8d:24:90:39
    q - quit


Select between 1 - 3: 2

### choice 2 selected.
### Deleting key: aaaa...
info. OK.

It deletes one key previous to the selection, and if you select 1, it deletes the last key (in this case 3).

Opened Bug #52 for the same.

**Comment by vaglomangirish** [comment]
Bug #53 found for an issue with cm key default.
Temporarily worked around by making implementation similar to that of cm key get.

**Comment by vaglomangirish** [comment]
Hello Prof. Gregor,
All the key commands in the list are now done, except for the one which would add key to git. As per your comment, this feature would be deferred as we only require to read git keys for now.
Please let me know if I can mark this item as closed.
Thanks.

**Comment by laszewsk** [comment]
dont do git add, ;-)
file bug, done …

**Comment by laszewsk** [comment]
e.g. create new issue if you have not done so.

**Comment by vaglomangirish** [comment]
Thanks for confirming Professor, we already have the issue raised #51.
Marking it done and closed.
