### ISSUE TITLE
scripts: sync script example does not work

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#140]
sync script example does not work due to ! bug

**Comment by laszewsk** [comment]
please keep sync script like this as it shows how to use it in conjunction with !

**Comment by laszewsk** [comment]
I fixed the ! bug with a workaround, but the sync command is not working in the script.

I delegate that issue to Gourav

**Comment by laszewsk** [comment]
subprocess.CalledProcessError: Command '['rsync', '~/cm_sync/put/*', 'india:sync_dir']' returned non-zero exit status 23

**Comment by gouravshenoy** [comment]
Refactored the ```sync``` command to now use ```rsync``` on both Windows and Linux (now that ```rsync``` works on Windows as well).
Verified ```sync``` command on Windows and Linux.
