### ISSUE TITLE
measuring limit and quota by NovaClient Python API

### ISSUE THREAD

**Issue by lee212** [cloudmesh/client#15]
{'india': {u'absolute': {u'maxImageMeta': 128,
                         u'maxPersonality': 5,
                         u'maxPersonalitySize': 10240,
                         u'maxSecurityGroupRules': 20,
                         u'maxSecurityGroups': 10,
                         u'maxServerGroupMembers': 10,
                         u'maxServerGroups': 10,
                         u'maxServerMeta': 128,
                         u'maxTotalCores': 20,
                         u'maxTotalFloatingIps': 10,
                         u'maxTotalInstances': 10,
                         u'maxTotalKeypairs': 100,
                         u'maxTotalRAMSize': 51200,
                         u'totalCoresUsed': 11,
                         u'totalFloatingIpsUsed': 0,
                         u'totalInstancesUsed': 10,
                         u'totalRAMUsed': 14848,
                         u'totalSecurityGroupsUsed': 1,
                         u'totalServerGroupsUsed': 0},
           u'rate': []}}
{'chameleon': {u'absolute': {u'maxImageMeta': 128,
                             u'maxPersonality': 5,
                             u'maxPersonalitySize': 10240,
                             u'maxSecurityGroupRules': 20,
                             u'maxSecurityGroups': 10,
                             u'maxServerGroupMembers': 10,
                             u'maxServerGroups': 10,
                             u'maxServerMeta': 128,
                             u'maxTotalCores': 16,
                             u'maxTotalFloatingIps': 8,
                             u'maxTotalInstances': 16,
                             u'maxTotalKeypairs': 100,
                             u'maxTotalRAMSize': 32000,
                             u'totalCoresUsed': 5,
                             u'totalFloatingIpsUsed': 0,
                             u'totalInstancesUsed': 3,
                             u'totalRAMUsed': 10240,
                             u'totalSecurityGroupsUsed': 1,
                             u'totalServerGroupsUsed': 0},

All:

I wrote yesterday a python prg to do two things.

a) use the python openstack v2 instead of the v1 API
b) see what default values are avalable to the users on chameleopn.

Based on this I can see that the limits are slightly differently set, which is expected, but this reminds us that we ought to check the actual limits set on india to make sure it does not exceed memory and stuff like this. 

PS: Despite the API bing available its not at all well documented to obtain this portion of information via the python API. For example I could not find a valid example on the internet or even in the openstack documentation on how to use that. I have a prg in test.py in cloudmesh client that shows how to do it. THis may be used as inspiration on how to get other info from nova … How to deal with flavor, images, and servers is well documented however. 

Please can you add this to the todo list

**Comment by laszewsk** [comment]
this is more for fugang and hyungro rather than cloudmesh
we may want to remove this issue here and move it to where 
fugang & badi maintain the things to do

**Comment by fugangwang** [comment]
We have used this:
http://developer.openstack.org/api-ref-compute-v2-ext.html#os-quota-sets <http://developer.openstack.org/api-ref-compute-v2-ext.html#os-quota-sets>
to obtain similar information. But this requires admin credential as it supports also the modification of quota.

The api doc for the limits and usage:
http://developer.openstack.org/api-ref-compute-v2-ext.html#os-used-limits <http://developer.openstack.org/api-ref-compute-v2-ext.html#os-used-limits>
