### ISSUE TITLE
Deploy: Dev environment for Linux (CentOS)

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#19]
Create the documentation and a script that deploys a development environment 

emacs
python >= 2.7.10
pip >= 1.7.2
virtualenv >= 13.1.2
setuptools >= 18.2

Note that much of this may be similar to linux other than installing cygwin

We need the following repos

cloudmesh/base
cloudmesh/cmd3
cloudmesh/client

So we do a source install

for a production install(which we do not yet have we use

pip install cloudmesh_base
pip install cmd3
pip install cloudmesh_client

We need to document in the manual the development deployment so we can do improvements and the user deployment. a note needs to be made to tell users for now to use the development deployment.

There is already documentation in the client manual

coordinate with others that do this for different OS
e.g. OSX, Windows 10, Centos, Ubuntu

**Comment by vaglomangirish** [comment]
Added a an initial version of the CentOS env setup documentation.
This would need some more work as follows:-
* [ ] Add steps to install emacs
* [ ] Add steps to install setuptools
* [ ] Add steps to check out the code repos from git
* [ ] Peer review

**Comment by vaglomangirish** [comment]
Moved to Oct 9 milestone as this needs some more work/ improvements and also a related bug #57 is planned for Oct 9.

**Comment by laszewsk** [comment]
cmd3 is no longer needed
