### ISSUE TITLE
Doc: Cmd3.yaml file documentation

### ISSUE THREAD

**Issue by paulo-chagas** [cloudmesh/client#2]
replace cloudmesh_client for cloudmesh_cloud

**Comment by laszewsk** [comment]
document 

cm plugins add cloudmesh_client

as part of the initialization. Put it at the right place, Gregor will do final documentation

* [ ] have you added this in this setup/initialization at proper location
* [ ] have you notified Gregor
* [ ] put in comment which file you added this to in this issue.

**Comment by laszewsk** [comment]
we are no longer using cmd3 so we do not need the yaml file
