### ISSUE TITLE
key: key_to_cloud_map in DB fails if the username is TBD

### ISSUE THREAD

**Issue by supreeth90** [cloudmesh/client#203]
P:11

We need to identify more details to decide if this is a task for Mangirish or if it is EC2 only so its a task for Supreeth

I am not sure if this is a valid bug which I discovered while adding support for libcloud. The issue here is that add a new SSH key-pair, then upload that to some cloud, then try to create a new VM on that same cloud using the same key-pair and this fails as TBD is considered None while writing to DB and TBD is considered literally while reading from the DB.

**Comment by laszewsk** [comment]
can you write own the exact cm commands that lead up to this so we can replicate and debug

**Comment by laszewsk** [comment]
key management has been rewritten so thsi should not be an issue anymore if key upload for cloud is provided in provider
