### ISSUE TITLE
travis failure

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#228]
Installed /home/travis/virtualenv/python2.7_with_system_site_packages/lib/python2.7/site-packages/pluggy-0.3.1-py2.7.egg
error: requests 2.8.1 is installed but requests>=2.10.0 is required by set(['python-keystoneclient', 'keystoneauth1'])

**Comment by badi** [comment]
Which travis build is this coming from?
#227 should solve this.

**Comment by laszewsk** [comment]
I replaced  setup.py with pip install, but it still fails

**Comment by fugangwang** [comment]
The latest build #1921 failed with this error at the end. I have fixed this in the dev branch (not yet merged to master).
======================================================================
ERROR: tests.cm_basic.test_cloud_model.Test_cloud_model.test_002
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/cloudmesh/client/client/tests/cm_basic/test_cloud_model.py", line 206, in test_002
    result = self.run("cm refresh off")
  File "/home/travis/build/cloudmesh/client/client/tests/cm_basic/test_cloud_model.py", line 47, in run
    result = Shell.execute(shell_command, args)
  File "/home/travis/build/cloudmesh/client/client/cloudmesh_client/common/Shell.py", line 357, in execute
    if result is None:
UnboundLocalError: local variable 'result' referenced before assignment

----------------------------------------------------------------------
Ran 24 tests in 2.570s

FAILED (errors=2)
[0m
travis_time:end:0f5ac7c4:start=1464301918216925591,finish=1464301921828609635,duration=3611684044
[0K
[31;1mThe command "nosetests -v --nocapture tests/cm_basic" exited with 1.[0m

Done. Your build exited with 1.

**Comment by fugangwang** [comment]
Although the version conflict error seems still there as well based on the log:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/133243156/log.txt

$ cm version

 <>Traceback (most recent call last):

 <>……

 <>pkg_resources.ContextualVersionConflict: (requests 2.8.1 (/home/travis/virtualenv/python2.7_with_system_site_packages/lib/python2.7/site-packages), Requirement.parse('requests>=2.10.0'), set(['python-keystoneclient', 'keystoneauth1']))

 <>
 <>
 <>The command "cm version" exited with 1.

**Comment by laszewsk** [comment]
I am actually confused about this as Badi mentioned he fixed this and I think it shows up also in dev and not just master.

**Comment by fugangwang** [comment]
For the latest code in dev branch I can run both ‘pip install .’ and ‘python setup.py install’ without seeing any issue.
In either case ‘cm version’ runs correctly as well.

For the latest code in master I see the same result - no issue at all.

So it must be some configuration in travis that caused the error.

**Comment by badi** [comment]
[Build #1922](https://travis-ci.org/cloudmesh/client/builds/133256835) is passing so I'm going to close this.
