### ISSUE TITLE
install: pip install . issues

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#229]
during the development pip install .does not work. It requires an uninstall of the package prior to running pip install .

This does not happen with python setup.py install

so we need to figure out how to properly use pip install . so it upgrades to a new version without resinstalling each package.

* [x] find a fix for the pip install . during development as pip install . recommended by Badi
* [x] This requires changes also in the documentation.

**Comment by fugangwang** [comment]
pip install -U . works

**Comment by badi** [comment]
As Fugang said: `pip install -U .` does this.
The documentation is updated in 27a124d
