### ISSUE TITLE
Doc: Error while running #make doc

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#23]
cm man > source/man/man.rst
CM             /cloudmesh_base/ConfigDict.pyc... site:144:  ERROR - The file /home/mangirish/.cloudmesh/cmd3.yaml fails with a yaml read error
CM             /cloudmesh_base/ConfigDict.pyc... site:145:  ERROR - Invalid placeholder in string: line 4, col 15
Traceback (most recent call last):
  File "/home/mangirish/ENV/bin/cm", line 9, in <module>
    load_entry_point('cmd3==3.2.0', 'console_scripts', 'cm')()
  File "/home/mangirish/ENV/lib/python2.7/site-packages/cmd3/shell.py", line 477, in main
    cmd.set_debug(properties["debug"])
UnboundLocalError: local variable 'properties' referenced before assignment
make[1]: *** [manpages] Error 1
make[1]: Leaving directory `/home/mangirish/github/cloudmesh/client/docs'
make: *** [doc] Error 2

**Comment by laszewsk** [comment]
does this error still exists as we removed dependency of cmd3?

**Comment by vaglomangirish** [comment]
I verified that the doc build works fine now:-

Cluster (do)
--------
/home/mangirish/github/cloudmesh/client/docs/source/old1.rst:821: WARNING: Title underline too short.

Admin (do)
------
/home/mangirish/github/cloudmesh/client/docs/source/old1.rst:821: WARNING: Title underline too short.

Admin (do)
------
/home/mangirish/github/cloudmesh/client/docs/source/system-cygwin.rst:98: WARNING: duplicate label windows-install, other instance in /home/mangirish/github/cloudmesh/client/docs/source/system.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/mangirish/github/cloudmesh/client/docs/source/commands_nova.rst:: WARNING: document isn't included in any toctree
/home/mangirish/github/cloudmesh/client/docs/source/commands_register.rst:: WARNING: document isn't included in any toctree
/home/mangirish/github/cloudmesh/client/docs/source/hacking.rst:: WARNING: document isn't included in any toctree
/home/mangirish/github/cloudmesh/client/docs/source/man.rst:: WARNING: document isn't included in any toctree
/home/mangirish/github/cloudmesh/client/docs/source/old1.rst:: WARNING: document isn't included in any toctree
/home/mangirish/github/cloudmesh/client/docs/source/system-cygwin.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] use                                                                                                                                            
generating indices... genindex
writing additional pages... search
copying images... [100%] images/git_setup/git_setup.png                                                                                                                 
copying static files... WARNING: html_static_path entry u'/home/mangirish/github/cloudmesh/client/docs/source/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 111 warnings.

Build finished. The HTML pages are in build/html.
make[1]: Leaving directory `/home/mangirish/github/cloudmesh/client/docs'

Marking the item as closed.
