### ISSUE TITLE
Console: global switch to switch on and off the color mode

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#24]
TODO: It would be good if the Console uses the borg pattern to have a
global switch for the console color mode. Currently each import
switches it back to color.

**Comment by gouravshenoy** [comment]
Implemented ColorCommand for switching console color mode ON/OFF.

One can switch the color mode on/off with
```python
cm color mode ON
cm color mode OFF
```

Color mode config set in the cloudmesh.yaml file - default = ON
```python
  system:
    data: ~/.cloudmesh/cloudmesh_inventory.yaml
    console_color: true
```
