### ISSUE TITLE
change call to novaclient Client to use kwargs as current approach is deprecated

### ISSUE THREAD

**Issue by badi** [cloudmesh/client#248]
# Description

The current approach calls to `Client` like so:
```python
            self.provider = client.Client(
                version,
                credentials["OS_USERNAME"],
                os_password,
                credentials["OS_TENANT_NAME"],
                credentials["OS_AUTH_URL"],
                cert)
```

This results in the warning:

> UserWarning: Only VERSION, USERNAME, PASSWORD, PROJECT_ID and AUTH_URL arguments can be specified as positional arguments. All other variables should be keyword arguments. Note that this will become an error in Ocata.

# Known components affected

`cm image refresh`

**Comment by badi** [comment]
See also #247

**Comment by fugangwang** [comment]
This was due to the historical reason when we have much older openstack and novaclient api that has to be supported. With the changing of API version we have to revisit this and make changes properly. For now let’s leave this open.
