### ISSUE TITLE
Deploy: windows: ssh

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#25]
we need some way in windows to configure the ssh client in the yam file. In cygwin there is no change, but if we have putty we need to use 

putty.exe -ssh username@198.18.14.10

However, maybe that is not needed  in case we are not using cygwin an ssh.bat or exe file that wraps the putty program and we can say 

ssh  username@198.18.14.10

straight from the command line. We can use in python the TERM variable to see if we are in cygwin or not

**Comment by laszewsk** [comment]
the latest documentation seems to do it, we need to make sure the documentation is up to date.

**Comment by gouravshenoy** [comment]
SSH seems to work fine by following latest documentation that uses chocolatey.
Steps include (In Powershell as administrator):
1. Install chocolatey.
2. Install posh-get via chocolatey.

**Comment by laszewsk** [comment]
can you verify if the documentation is ok?

Also we need to have working python documentations …

Once Erika or you have tested this on either your vms, or a vanilla machine here at my office this can be closed.

**Comment by gouravshenoy** [comment]
Updated the documentation with latest steps.
Followed the documentation on vanilla Windows 10 vm on my virtualbox, and it seems to work fine.
