### ISSUE TITLE
Command: register from os.environ

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#26]
Assume a user has an openstack client registered in the os.environ

add a new option to register that allows to integrat it into the yaml file

cm register [--provider=openstack] env  [HOST]

provider default: openstack
HOST default if None: localhost

**Comment by laszewsk** [comment]
maybe it should be similar to the RC command
cm register env 
cm register env localhost 

if --provider is not specified openstack is used

**Comment by laszewsk** [comment]
duplicated by #43

**Comment by vaglomangirish** [comment]
Need some info about the [HOST] parameter...
Does it mean that the command should read env variables from remote host if not localhost?
Currently the implementation in #43 is valid only for localhost. Please let me know if it should support remote hosts as well.
Thanks.

**Comment by vaglomangirish** [comment]
Enabled the cm register env command:-

    $ cm register env
    Cloud name (Default: i5r.idp.iu.futuregrid.org): futuregrid
    cm_heading (Default: i5r.idp.iu.futuregrid.org Cloud): 
    cm_host name (Default: i5r.idp.iu.futuregrid.org): 
    cm_label name (Default: i5r.idp.iu.futuregrid.org): future label
    cm_type name (Default: openstack): 
    cm_type_version name (Default: null): 
    New cloud config exported to /home/mangirish/.cloudmesh/cloudmesh.yaml

In cloudmesh.yaml:-

        OS_USERNAME: vagloman
    futuregrid:
      cm_heading: i5r.idp.iu.futuregrid.org Cloud
      cm_host: i5r.idp.iu.futuregrid.org
      cm_label: future label
      cm_type: openstack
      cm_type_version: null
      credentials:
        OS_AUTH_URL: https://i5r.idp.iu.futuregrid.org:5000/v2.0
        OS_CACERT: location/cacert.pem
        OS_PASSWORD: **********         # Password suppressed for security reason
        OS_TENANT_NAME: fg478
        OS_USERNAME: vagloman

This issue can be closed if only the local environment variables reading is sufficient.
It may need more work if this requires remote host environment variable reading as well.

**Comment by laszewsk** [comment]
you may want to add small explanation on what the cm_* are used for. 

Remember you can “invent” these fields and use them in the db and your programs. Also you do not necessarily in the command mention the cm_

Label:
	This is a human readable label that can be associated with the cloud. 

		Mangirish: It is the SAME as the cloudname in the yaml file

			e.g.

				india:
					label: india

Heading:
	This is used in case the cloud name is too long and is often the same as the label

Hostname:  This is a name of a login machine that may be associated with this cloud. 
	By default it is None

Type: This is the type of the cloud, you may only select from
	openstack, azure, aws

Type version:
	The version for the particular cloud. Default is None.
	Fur example in case of openstack, chose kilo, juno, ...

**Comment by vaglomangirish** [comment]
Thanks for the info Professor.

I have changed the prompt messages to be more descriptive. Also, I have removed the [HOSTNAME] parameter from the command (not from the cloud object to be added), to avoid confusion.

If user supplies the --provider it is considered as cm_type. I have added validation to check if it is one of openstack/ azure/ aws.

    $ cm register env
    Name of the cloud (Default: i5r.idp.iu.futuregrid.org): Demo
    Label for the cloud (Default: Demo): 
    Heading for the cloud (Default: Demo Cloud): 
    Cloud host name (Default: i5r.idp.iu.futuregrid.org): 
    Type of the cloud- openstack/azure/aws (Default: openstack): azure
    Version of type azure (Default: null): V2
    Default flavor for the cloud instances (Default: null): tiny
    Default image for the cloud instances (Default: null): ubuntu
    Default location for the cloud instances (Default: null): WestDC
    New cloud config exported to /home/mangirish/.cloudmesh/cloudmesh.yaml

In the yaml:-

        image: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2-LTS-amd64-server-20150610-en-us-30GB
        location: East US
    Demo:
      cm_heading: Demo Cloud
      cm_host: i5r.idp.iu.futuregrid.org
      cm_label: Demo
      cm_type: azure
      cm_type_version: V2
      credentials:
        OS_AUTH_URL: https://i5r.idp.iu.futuregrid.org:5000/v2.0
        OS_CACERT: /home/mangirish/.cloudmesh/clouds/india/juno/cacert.pem
        OS_PASSWORD: uEnV1P69vmv5
        OS_TENANT_NAME: fg478
        OS_USERNAME: vagloman
      default:
        flavor: tiny
        image: ubuntu
        location: WestDC
  keys:

I am marking this issue closed, but please reopen if you think it requires any further change after the review.
