### ISSUE TITLE
Command: register nosetests

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#28]
Currently the manual page includes the following. Devise a ssufficient number of nosetests to verify that the command works and create a nosetest for it.

* [x] make sure these are all the command options we need
* [x]              register info
* [x]              register list [--yaml=FILENAME]
* [x]              register list ssh
* [x]              register cat [--yaml=FILENAME]
* [x]              register edit [--yaml=FILENAME]
* [x]              register form [--yaml=FILENAME]
* [x]              register check [--yaml=FILENAME]
* [x]              register test [--yaml=FILENAME]
* [x]              register rc HOST [OPENRC]
* [x]              register json HOST
* [x]              register merge FILEPATH
* [x]              register india [--force]
* [x]              register CLOUD CERT [--force]
* [x]              register CLOUD --dir=DIR

* [x] update the documentation
* [x] make sure we have examples

**Comment by ehdsouza** [comment]
Implemented, tested and documented register commands.

For cm register test, created a separate issue to be implemented in oct: https://github.com/cloudmesh/client/issues/49
