### ISSUE TITLE
Command: group: Implement Group Command

### ISSUE THREAD

**Issue by gouravshenoy** [cloudmesh/client#29]
* [x] I have already added skeleton methods for this command; need to now add business logic for implementation. 
* [x] nosetests
* [x] documentation with examples

**Comment by laszewsk** [comment]
Gurav reported in #30: I have already added nosetests for the skeleton methods implemented. Once business logic is implemented, need to enhance the tests.

**Comment by gouravshenoy** [comment]
Implemented the following group commands:
              group info [--format=FORMAT]
              group add [--name=NAME] [--type=TYPE] --id=IDs
              group list [--cloud=CLOUD] [--format=FORMAT] NAME
              group delete [--cloud=CLOUD] [--name=NAME]
              group copy FROM TO
              group merge GROUPA GROUPB MERGEDGROUP

**Comment by gouravshenoy** [comment]
Added nosetests for above implementation

**Comment by gouravshenoy** [comment]
Made following changes to syntax of _**"group list"**_ & _**"group info"**_ commands:

* **Previously:**
  * group info [--format=FORMAT]
  * group list [--cloud=CLOUD] [--format=FORMAT] NAME

* **Now:**
  * group info [--format=FORMAT] NAME
  * group list [--cloud=CLOUD] [--format=FORMAT]

**Comment by gouravshenoy** [comment]
Added command_group.rst file that contains examples of _**group <command>**_.
Also the man.rst has been updated with latest docopts.
