### ISSUE TITLE
Command: secgroup: implement & test

### ISSUE THREAD

**Issue by gouravshenoy** [cloudmesh/client#31]
Need to implement the security group command & add nosetests for the implementation.

* [x] documentation in docopt
* [ ] review with team, comment results in this issue with changes
* [ ] implement
* [ ] nosetests

**Comment by gouravshenoy** [comment]
Implemented _**cm secgroup create <args>**_ and __**cm secgroup list <args>**_ commands.

**Comment by laszewsk** [comment]
very good!

cloud and tenant should be optional and set via default

**Comment by gouravshenoy** [comment]
Implemented _**cm secgroup rules-add**_ and _**cm secgroup rules-list**_ commands.
Added nosetests for above commands
Added examples in RST document for above commands

**Comment by gouravshenoy** [comment]
**TODO:** Make _tenant_ and _cloud_ arguments optional, & read from default.

**Comment by gouravshenoy** [comment]
Implemented _**cm secgroup delete**_ and _**cm secgroup rules-delete**_ commands.
Added nosetests for above commands
Added examples in RST document for above commands

**Comment by gouravshenoy** [comment]
Updated all commands to make _**cloud**_ and _**tenant**_ as optional arguments, and read from default value set.
Man page has been also updated with latest syntax.
