### ISSUE TITLE
Command: fix topics

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#33]
when doing cm help you see some topics. make sure they are correct.

* [x] add the command version to the topic "shell"
* [x] add the command help to the topic "shell"
* [x] add the command pause to the topic "shell"
* [x] add the command quit to the topic "shell"
* [x] add the command server to the topic "cloud"
* [x] add the command reservation to the topic "cloud"
* [x] add the command register to the topic "cloud"

**Comment by ehdsouza** [comment]
reservation command is added to system, should it be cloud??
