### ISSUE TITLE
Command: vm: group management

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#35]
* [x] add to this task if you see something missing
* [x] add vms started with the nova command to default group
* [x] add a group parameter to be able to overwrite the default group
* [x] test the listing of nova started vms to the groups
* [x] develop nosetests
* [x] test on cloud juno 

   * [x] list
   * [x] delete

* [x] test on cloud kilo

   * [x] list
   * [x] delete

* [x] test on both clouds at the same time

   * [x] list
   * [x] delete

**Comment by gouravshenoy** [comment]
Implemented Group management for VM command. 

Added a new _--group_ parameter to specify the group to add the VM to. If not specified, then it reads the default group value set using default command.
