### ISSUE TITLE
Admin: get accounts on chameleon and kilo

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#36]
* [x] task for all three of you, Erika will make sure you execute. Getting accounts may take some time. 
* [x] send singel e-mail with account names for each cloud so Gregor adds you to project
* [x] Gregor adds you to fg82 project on chameleon
* [x] Fugang will create project on kilo, communicate with Fugang, we will use your current project and not fg82

kilo - get account on kilo, talk to kevinwangfg@gmail.com (He sits upstairs)

  * [x] Gregor
  * [x] Erika
  * [x] Gourav
  * [x] Mangirish

Chameleon - get account on https://www.chameleoncloud.org

  * [x] Gregor
  * [x] Erika
  * [x] Gourav
  * [x] Mangirish

**Comment by ehdsouza** [comment]
Chameleon and kilo accounts have been created for all
