### ISSUE TITLE
Command: register: Wrong ConfigDict

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#38]
Naturally we want to use the ConfigDict from client and not the one form base.

I saw this

from cloudmesh_base.ConfigDict import ConfigDict as BaseConfigDict

**Comment by ehdsouza** [comment]
Removed the usage of ConfigDict from base:
https://github.com/cloudmesh/client/commit/d8eed0cae8e21accd2a1a397338f0bd6952fb0b8
