### ISSUE TITLE
Develop vm command

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#42]
* [x] Gregor added vm command from old dir
* [x] Develop a provider for India cloud.
* [x] Develop a command that uses the default or specified cloud to create vms

* [x] vm start [--name=NAME]
                         [--count=COUNT]
                         [--cloud=CLOUD]
                         [--image=IMAGE_OR_ID]
                         [--flavor=FLAVOR_OR_ID]
                         [--group=GROUP]
* [x] vm delete [NAME_OR_ID...]
                          [--group=GROUP]
                          [--cloud=CLOUD]
                          [--force]
* [x] vm floating_ip_assign [NAME_OR_ID...]
                             [--cloud=CLOUD]
* [x] vm ip_show [NAME_OR_ID...]
                           [--group=GROUP]
                           [--cloud=CLOUD]
                           [--format=FORMAT]
                           [--refresh]
* [x] vm login NAME [--user=USER]
                         [--ip=IP]
                         [--cloud=CLOUD]
                         [--key=KEY]
                         [--command=COMMAND]
* [x] vm list [CLOUD|--all]
                        [--group=GROUP]
                        [--refresh]
                        [--format=FORMAT]
                        [--columns=COLUMNS]
                        [--detail]

* [x] Test with India cloud provider
* [x] Add man and command pages for vm command
* [ ] Develop nosetests

**Comment by laszewsk** [comment]
I added old vm command to commands, remember that may not be correct

**Comment by vaglomangirish** [comment]
Hello Prof. Gregor,

I have just delivered the IndiaCloudProvider and `cm vm start` and `cm vm delete` implementations.
I have made the VmCommand fetch the cloud provider object dynamically based on cloud (default as India) with the help of a utility class cloudmesh_client.cloud.vm.Vm

Could you please review this implementation and let me know if I can proceed with this for further commands?

I tested it for the start and delete and it works well with India cloud.

Thanks.

**Comment by vaglomangirish** [comment]
$ cm vm start --name=startwithvm --cloud=india --image=619b8942-2355-4aa2-bae3-74b8f1751911 --flavor=1
/home/mangirish/ENV/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/mangirish/ENV/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
### Machine startwithvm is being booted on India Cloud...


$ cm nova list
Cloud = india
+--------------------------------------+--------------+--------+------------+-------------+--------------------------------------+
| ID                                   | Name         | Status | Task State | Power State | Networks                             |
+--------------------------------------+--------------+--------+------------+-------------+--------------------------------------+
| 94f01af3-ee2a-44c9-b228-75627f358169 | ehdsouza-001 | ACTIVE | -          | Running     | int-net=10.23.3.229, 149.165.158.112 |
| 21305503-2649-4338-8876-d825758c83f3 | goshenoy-001 | ACTIVE | -          | Running     | int-net=10.23.3.214, 149.165.158.110 |
| 6437e054-b761-4408-890a-ced65cc848e2 | goshenoy-002 | ACTIVE | -          | Running     | int-net=10.23.3.56, 149.165.158.228  |
| 760d5701-ddeb-45cf-864b-92c3cd5db552 | mango-001    | ACTIVE | -          | Running     | int-net=10.23.3.102                  |
### | f3a3c167-1964-4570-ba38-cdd123f6d823 | startwithvm  | ACTIVE | -          | Running     | int-net=10.23.1.171                  |
+--------------------------------------+--------------+--------+------------+-------------+--------------------------------------+


$ cm vm delete --cloud=india f3a3c167-1964-4570-ba38-cdd123f6d823
/home/mangirish/ENV/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/mangirish/ENV/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/mangirish/ENV/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
### Machine ['f3a3c167-1964-4570-ba38-cdd123f6d823'] is being deleted on India Cloud...

**Comment by laszewsk** [comment]
Improvements: think about it firts befor doing it if this makes sense

* [ ] should be openstack provider and not india provider as generally useful.
* [ ] we may have to change 

 self.nova = client.Client(version, self.credentials["OS_USERNAME"], self.credentials["OS_PASSWORD"],
                                  self.credentials["OS_TENANT_NAME"], self.credentials["OS_AUTH_URL"],
                                  self.credentials["OS_CACERT"])

to 

 self.nova = client.Client(version, self.credentials)

as we do not know exactly whats in credential and we probably need to iterate over it in Client

* [ ] We need to add function 

export_credentials, that writs openrc.sh like info when we call it

**Comment by vaglomangirish** [comment]
Hello Professor,

Thanks for suggesting the improvements. I had a few questions before I proceed implementing it:-

1. should be openstack provider and not india provider as generally useful.
  ---> I intended doing that initially, but later thought of making a separate provider as I thought it would serve to isolate each cloud better and we can implement any cloud functionalities easily going ahead. In earlier care, the change in generic openstack provider is likely to affect all the openstack based clouds, whereas a change in Cloud specific provider will have limited impact.
Can we instead use a pattern wherein IndiaCloudProvider inherits the generic openstack provider instead?

2. export_credentials, that writs openrc.sh like info when we call it --> Is this what we intend to achieve with the 'sh' format of output in os_vars_to_yaml.py script (Issue #43 )?

3. Regarding self.nova = client.Client(version, self.credentials):-
---> Do you mean we could have a wrapper function for client.Client which uses export_credentials script to call the actual client.Client?

**Comment by laszewsk** [comment]
> On Sep 26, 2015, at 11:55 AM, Mangirish Wagle <notifications@github.com> wrote:
> 
> Hello Professor,
> 
> Thanks for suggesting the improvements. I had a few questions before I proceed implementing it:-
> 
> should be openstack provider and not india provider as generally useful.
> ---> I intended doing that initially, but later thought of making a separate provider as I thought it would serve to isolate each cloud better and we can implement any cloud functionalities easily going ahead. In earlier care, the change in generic openstack provider is likely to affect all the openstack based clouds, whereas a change in Cloud specific provider will have limited impact.
> Can we instead use a pattern wherein IndiaCloudProvider inherits the generic openstack provider instead?
> 
> 
providers for chameleoon, kilo and openstack should be similar.

> export_credentials, that writs openrc.sh like info when we call it --> Is this what we intend to achieve with the 'sh' format of output in os_vars_to_yaml.py script (Issue #43 <https://github.com/cloudmesh/client/issues/43> )?
> 
> 
we need some command in shell that “prints” what we have in openrc.sh, this way we can paste and copy and execute that …
number 43 does the invers, read the openrc.sh and integrate it in cloudmesh.yaml
> Regarding self.nova = client.Client(version, self.credentials):-
> ---> Do you mean we could have a wrapper function for client.Client which uses export_credentials script to call the actual client.Client?
> 
not sure i understand. we always want to read from yaml for normal cases. if credentials not in yaml we use your env reade to create credentials.

**Comment by vaglomangirish** [comment]
Managed to boot, delete, list and 'ip_show' for vms on india and chameleon clouds.
Attaching a txt containing outputs of sample runs of vm command.

Please note that I had to do the following manual changes to get it working:-
1) Add chameleon cloud to ~/.cloudmesh/cloudmesh.yaml
2) Add OS_CACERT=null to chameleon credentials

[vm_run.txt](https://github.com/cloudmesh/client/files/7378/vm_run.txt)

**Comment by laszewsk** [comment]
very good!

good that you noticed a workaround, this will help us fixing teh solution.

looks like

a) etc yaml file need sto be ubdated
b) we need to anticipate clouds in register that do not have certs … e.g. if its not specified we simply do not pass it along, or do as you say pass null along, but that seems a bit ugly. so change may need to be made to identify **data structure with kwargs and make sure that if cacert is not there not to add it to **data and than use Client(**data)

**Comment by vaglomangirish** [comment]
Implemented the vm login and vm floating_ip_assign commands, tested successfully on India cloud.
Attaching the test runs of all the vm commands.
[VMTest.txt](https://github.com/cloudmesh/client/files/15802/VMTest.txt)

**Comment by laszewsk** [comment]
Mangirish: Implemented the vm login and vm floating_ip_assign commands, tested successfully on India cloud. Attaching the test runs of all the vm commands.
