### ISSUE TITLE
Command: Quota

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#46]
* [x] docopts
* [x] implement cloud/Quota class
* [x] implement quota command
* [x] Nosetest
* [x] documentation

**Comment by ehdsouza** [comment]
Implemented quota list:
C:\Users\erika> cm quota india
+-----------------------------+-------+
| Quota                       | Limit |
+-----------------------------+-------+
| fixed_ips                   | -1    |
| floating_ips                | 10    |
| instances                   | 10    |
| security_groups             | 10    |
| server_group_members        | 10    |
| server_groups               | 10    |
| key_pairs                   | 100   |
| injected_file_content_bytes | 10240 |
| metadata_items              | 128   |
| cores                       | 20    |
| security_group_rules        | 20    |
| injected_file_path_bytes    | 255   |
| injected_files              | 5     |
| ram                         | 51200 |
+-----------------------------+-------+

**Comment by ehdsouza** [comment]
Completed the quota command along with documentation and nosetests.
