### ISSUE TITLE
Command: limits

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#47]
* [x] docopts
* [x] implement cloud/Limits class
* [x] implement limits command
* [x] Nosetest
* [x] documentation

**Comment by ehdsouza** [comment]
Implemented limits command:
PS> cm limits list --cloud=india
+--------------------+------+-------+
| Name               | Used | Max   |
+--------------------+------+-------+
| FloatingIps        | 0    | 10    |
| Instances          | 4    | 10    |
| SecurityGroups     | 1    | 10    |
| ServerGroupMembers | -    | 10    |
| ServerGroups       | 0    | 10    |
| Keypairs           | -    | 100   |
| Personality Size   | -    | 10240 |
| ImageMeta          | -    | 128   |
| Server Meta        | -    | 128   |
| Cores              | 4    | 20    |
| SecurityGroupRules | -    | 20    |
| Personality        | -    | 5     |
| RAM                | 8192 | 51200 |
+--------------------+------+-------+

**Comment by ehdsouza** [comment]
Altered code to use python api for limits...

C:\Users\erika> cm limits list
+-------------------------+-------+
| Name                    | Value |
+-------------------------+-------+
| maxImageMeta            | 128   |
| maxPersonality          | 5     |
| maxPersonalitySize      | 10240 |
| maxSecurityGroupRules   | 20    |
| maxSecurityGroups       | 10    |
| maxServerGroupMembers   | 10    |
| maxServerGroups         | 10    |
| maxServerMeta           | 128   |
| maxTotalCores           | 20    |
| maxTotalFloatingIps     | 10    |
| maxTotalInstances       | 10    |
| maxTotalKeypairs        | 100   |
| maxTotalRAMSize         | 51200 |
| totalCoresUsed          | 4     |
| totalFloatingIpsUsed    | 0     |
| totalInstancesUsed      | 4     |
| totalRAMUsed            | 8192  |
| totalSecurityGroupsUsed | 1     |
| totalServerGroupsUsed   | 0     |
+-------------------------+-------+
