### ISSUE TITLE
Command: List

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#48]
* [x] docopts
* [x] implement ListCommand class
* [x] implement List command
* [x] Nosetest
* [x] documentation

**Comment by gouravshenoy** [comment]
Implemented the ListCommand.
Updated the docopts for ListCommand.
Added nosestests for the command.

**Comment by gouravshenoy** [comment]
List Command syntax is as follows:

list [--cloud=CLOUD] [--format=FORMAT] default
                list [--cloud=CLOUD] [--format=FORMAT] vm
                list [--cloud=CLOUD] [--format=FORMAT] flavor
                list [--cloud=CLOUD] [--format=FORMAT] image

**Comment by gouravshenoy** [comment]
Will update the examples RST document for ListCommand shortly

**Comment by laszewsk** [comment]
you may have to add [—user=username] [—project=project] that use default value ...

we may also do —all that bypasses default values.

not thought much about this yet though

**Comment by gouravshenoy** [comment]
Added examples for List Command to _**command_list.rst**_

**Comment by gouravshenoy** [comment]
Added _**--user**_ and _**--tenant**_ arguments to the List Command.
Updated the man.rst with necessary docopt syntax

**Comment by laszewsk** [comment]
man.rst is automatically generated from the man page, did you update man.rst by hand? This will not work

**Comment by gouravshenoy** [comment]
Sorry, my statement seem to be misleading. I meant that the man.rst (which was generated automatically by _make doc_) has been committed.
