### ISSUE TITLE
Stalled: Github key adding

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#51]
Currently stuck on getting the github authentication working fine for cm key add --git.
The basic auth works fine, however the subsequent call to add the key still fails with 401 Unauthorized.
Code snippet:-

sshkey = SSHkey(file_path)
git_url = "https://api.github.com"
\# Basic Authenticate with git
print("Authenticating with username = {:} password = {:}".format(username, password))
r = requests.get("{:}/user".format(git_url), auth=(username, password))
print("Return code: {:}".format(r.text))
if (r.status_code == 200):
print("Git auth success")
payload = {
"title": gitkeyname,
"key": sshkey
}
r = requests.post("{:}/user/keys".format(git_url), data = payload, auth=(username, password))  <<--- FAILING AT THIS CALL
print("Response after post: {:}".format(r.text))
else:
raise Exception("Git Authentication Failed")

Please note that the print statements in the snippet are for debug purpose only and will be removed while delivering the code.

**Comment by laszewsk** [comment]
This activity is stalled, as we assume the user has uploaded the key to github. What we assume is that the user can read the key from github. We just need to provide in teh documentation a link to the page how to upload a key to github. We could make a new page for that but it does not need to be in the main documentation page, but just a subpage as a tip.

**Comment by laszewsk** [comment]
key have been rewritten by Gregor
