### ISSUE TITLE
Documentation: Centos system preparation

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#57]
I found some bugs in documentation that I mostly improved.

However we still have to verify if 

pip and virtualenv comes with python 2.7.10 and does not require yum install.

In case of yum install, the yum repo needs to specified that holds 2.7.10, or we need to specify on command line. see centos SLC.

However as i did not know how this works the save way to do it is to use the source install. I am not sure if we do source if we need to more clearly specify either do source or do youm, but i think the yum install is broken?

I like to propose the following:

* [ ] Install fresh version of CentOS on virtualbox
* [ ] test out your instructions up to the T but make sure you do not introduce unnecessary steps.

All we need is python 2.7.10, pip 7.1.2, virtualenv

furthermore we need possibly readline and pycrypoto (both are probably installed later, so you need to check if install works thus we do not have to add them here. IN OSX I do have to explicitly add them)

**Comment by vaglomangirish** [comment]
Modified the centos setup instructions after trying and experimenting on centos VM in India cloud.
The steps may need double verification.
