### ISSUE TITLE
command: key - debug messages

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#59]
Mangirish, there are lost of debug messages in the key commands you documented, can you do something better than just print 

none
delete
...

this seems rather confusing to just have some debug messages showing up ...

**Comment by vaglomangirish** [comment]
Delivered the changes that would remove the unwanted debug messages and updated the manual as well.

Responses to the review questions earmarked in the doc:-
1) Regarding 'cm key get', I assumed it to be just retrieving the key and printing its fingerprint. The actual purpose is not known to me either.

2) Regarding 'is_default' and why not 'default' attribute to handle default key... I had tried initially with 'default' but it gave several issues as 'default' is also a reserved word in sqlalchemy. Hence switched to 'is_default'.

Marking this issue as closed.
