### ISSUE TITLE
[reservation command] change the start and end time to 'datetime' format and not just date

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#65]
* [ ] Integrate cloudmesh/timestring library for the same

**Comment by vaglomangirish** [comment]
Need some info on how do we instantiate Date object in timestring library. I am trying the following as an experiment:-

    start_time = "1901-01-01 00:00"
    end_time = "2100-12-31 23:59"

    stime = Date(start_time)
    etime = Date(end_time)

It gives the error:-

    Traceback (most recent call last):
      File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client/shell/plugins    /ReservationCommand.py", line 206, in do_reservation
        etime = Date(end_time)
      File "build/bdist.linux-x86_64/egg/timestring/Date.py", line 156, in __init__
        new_date = new_date.replace(month=int(max(month)) if re.match('^\d+$', max(month)) else     dict(january=1, february=2, march=3, april=4, june=6, july=7, august=8, september=9, october=10, november=11, december=12, jan=1, feb=2, mar=3, apr=4, may=5, jun=6, jul=7, aug=8, sep=9, sept=9, oct=10, nov=11, dec=12).get(max(month),  new_date.month))
    ValueError: month must be in 1..12

    month must be in 1..12

**Comment by laszewsk** [comment]
https://github.com/stevepeak/timestring/blob/master/tests/tests.py <https://github.com/stevepeak/timestring/blob/master/tests/tests.py>

**Comment by vaglomangirish** [comment]
Facing one issue with the timestring library. The time component does not seem to be captured correctly:-

Trying the following:-

    start_time = Date("12/24/2015 at 03.30 pm")
    end_time = Date("02/22/2016 at 08.45 am")

    print("start time clock: {:}:{:}".format(start_time.hour, start_time.minute))
    print("end time clock: {:}:{:}".format(end_time.hour, end_time.minute))

It is printing:-
    start time clock: 0:0
    end time clock: 0:0

Same goes when I try using 24 hours format:-

    start_time = Date("12/24/2015 at 15.30")
    end_time = Date("02/22/2016 at 08.45")

**Comment by laszewsk** [comment]
isnt time

3:30pm

15:30

?

e.g. : and not .

**Comment by vaglomangirish** [comment]
Updated the reservation command to use datetime format for start and end times, by integrating the timestring library.
Updated nosetests and command manual examples.
