### ISSUE TITLE
Command: Images

### ISSUE THREAD

**Issue by ehdsouza** [cloudmesh/client#68]
* [x] docopts
* [x] implement cloud/Imagesclass
* [x] implement images command
* [x] Nosetest
* [x] documentation

**Comment by ehdsouza** [comment]
Implemented refresh and list:

F:\ClaudNauts> cm image refresh
Images for cloud india refreshed successfully
F:\ClaudNauts> cm image list
+-------+--------------------------------------+-----------------------------------------+
| cloud | uuid                                 | name                                    |
+-------+--------------------------------------+-----------------------------------------+
| india | 66708636-5ed6-4908-b36a-f5a69f8ac7ee | futuresystems/ubuntu-14.04              |
| india | f2c2bbda-8bc1-4f02-a2e8-60014da66689 | cloudmesh/ipynb-n-java                  |
| india | 85fdb68e-8bd3-4e5e-bb4e-f286298f4fe6 | said/ubuntu15                           |
| india | 7ddc3366-73bf-453a-a813-43514030bf2e | badi/centos-7-2015-06-01                |
| india | c3c5b676-be53-4237-a40f-451d4c6e572e | badi/ubuntu-14.04-2015-06-01            |
| india | 367de5c7-3a30-4bad-b316-1a2afa17d794 | futuresystems/ubuntu-12.04              |
| india | 619b8942-2355-4aa2-bae3-74b8f1751911 | CentOS-7                                |
| india | 132c961f-bca8-4942-a2c5-a8f60f84aea9 | lee212/CoreOS-Alpha                     |
| india | 364bd53b-87d3-4ac6-8e41-af540301f0cd | futuresystems/centos-7                  |
| india | a59833a2-60c9-47f0-b333-4e0bc071ac3a | futuresystems/hadoop-v2                 |
| india | 5337a50d-4418-4c1f-9741-5c31bf03e267 | lee212/CoreOS                           |
| india | e8acb8e0-fbc9-44e4-9b31-3c38fc9c25ae | lee212/boot2docker                      |
| india | f63a996c-ea69-4a56-830e-c190bca2f828 | VM with Cloudmesh Configured Completely |
| india | e3d5fcf5-1b40-48df-9098-3c03a682421e | slaves_ubuntu_14_04                     |
| india | 0f787e59-6ff9-466c-aaf6-cd3f3c9350d0 | kilitbilgi/ubuntu_14_10_desktop         |
| india | 186592ce-eed5-4631-bc0c-7022eccd8508 | fg464/hadoop-b649                       |
| india | b073ddce-747d-4c66-8152-70118a4e5781 | mooc-backup                             |
| india | 58c9552c-8d93-42c0-9dea-5f48d90a3188 | ubuntu12-cometworker1                   |
| india | 58e5d678-79ec-4a4d-9aa8-37975b7f40ac | futuresystems/fedora-21                 |
+-------+--------------------------------------+-----------------------------------------+

**Comment by ehdsouza** [comment]
Corrected the list attributes order and imeplementd 
> cm image show 58c9552c-8d93-42c0-9dea-5f48d90a3188 --live

**Comment by laszewsk** [comment]
is it possible to also ask by name e.g. command will autodetect if uuid or name

**Comment by ehdsouza** [comment]
The openstack python api get function takes the uuid of the image. 
But its possible, I can search the id of the image using the name in the local db, is it acceptable?

**Comment by laszewsk** [comment]
Sure I think in live mode you can do either anyways

**Comment by ehdsouza** [comment]
Completed image refresh, list and details

**Comment by laszewsk** [comment]
cm image refresh
juno
...

see the cloudname, somewhere we print this as debug statement, not sure if its in other commands also, can we locate where it comes from and remove

**Comment by ehdsouza** [comment]
Commented out the debug message:

cm image refresh --cloud=juno
Refresh image for cloud juno. ok.
