### ISSUE TITLE
Keys: Start implementing the keys plugin command

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#7]
We need to look into the old cloudmesh code and identify useful functions that we need in the new code.

* [x] implement a --select option that puts up a menu as part of the plugin command, but put it actually in sshkeys = SSHKeyManager(); key = sshkeys.select(); than we can reuse that in the plugin
* [x] introduce a new data table in sqlalchemy KEY that can be used to store the major key data. The data we take simply form the dict we have in SSHKey
* [x] introduce a new class SSHKeyDBManager that uses SSHKeyManager, and updates information to the database
* [x] implement a delete function in SSHKeyDBManager and  SSHKeyManager
* [x] develop unit tests SSHKeyDBManager
* [x] create a documentation template in docs/sources for key management. Focus on important issues. Use bullet points and ::, Gregor will write documentation based on that

This will also get into sqlalchemy as we introduce new KEY table. Nice thing is that this is all you.
However, make sure to check in frequently with me in regards to design. We want to make this simple and not replicate what is already done in CloudmeshDatabase. For example we shoudl use all the functions to add stuff to the DB from there instead of doing SQLalcheie or direct SQL calls. This increases portability. This use find, add, delete, functions from CloudmeshDatabase

Remember to also look into the old cloudmesh command for keys to see if there is something to do.

Also noice the possibility to return from a command if a rule fired, this could simplify the if condition.

**Comment by paulo-chagas** [comment]
This select option is for the key command right? this menu will show the
keys available to choose?
This menus is that one you said that is on cloudmesh_base?

**Comment by laszewsk** [comment]
yes, its for the key command,

**Comment by laszewsk** [comment]
Please provide in docs/source

keys.rst with bullet template, and some examples with ::

I will clean up grammar and formulate bullets into documentation. Send me mail when done.

**Comment by laszewsk** [comment]
much ofthis has been implemented.

**Comment by vaglomangirish** [comment]
Added key manual and example page to documentation.
