### ISSUE TITLE
[Nova Command] Cloud set by 'cm nova set <cloud>' does not persist

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#72]
If I run:-

    $ cm nova set kilo
    kilo is set

And then if I try listing instances:-

    $ cm nova list
    Cloud = india
    +--------------------------------------+--------------+--------+------------+-------------+--------------------------------------+
    | ID                                   | Name         | Status | Task State | Power State | Networks                             |
    +--------------------------------------+--------------+--------+------------+-------------+--------------------------------------+
    | 94f01af3-ee2a-44c9-b228-75627f358169 | ehdsouza-001 | ACTIVE | -          | Running     |     int-net=10.23.3.229, 149.165.158.112 |
    | 21305503-2649-4338-8876-d825758c83f3 | goshenoy-001 | ACTIVE | -          | Running     | int-net=10.23.3.214, 149.165.158.110 |
    | 6437e054-b761-4408-890a-ced65cc848e2 | goshenoy-002 | ACTIVE | -          | Running     | int-net=10.23.3.56, 149.165.158.228  |
    | 760d5701-ddeb-45cf-864b-92c3cd5db552 | mango-001    | ACTIVE | -          | Running     | int-net=10.23.3.102                  |
    +--------------------------------------+--------------+--------+------------+-------------+--------------------------------------+
    info. OK.

It still considers India cloud.

The set cloud gets overriden on every new instance of nova command run.

We need a way to persist the set cloud across nova command runs...

**Comment by vaglomangirish** [comment]
Hello Prof. Gregor and All,

Please suggest what would be the best place to persist the set cloud.
Can it be somewhere in cloudmesh.yaml? or the db?

Can I possibly set and use the 'active' cloud in cloudmesh.yaml for this?

**Comment by laszewsk** [comment]
default cloud kilo
default cloud chameleon

than either

nova boot
or
vm boot

should use the default cloud ….

it wil be overwritten by 

cm —cloud=india boot

this is also how image, flavor, key, and other defaults work

**Comment by vaglomangirish** [comment]
This issue is fixed after Defaults were integrated with nova command. Marking closed.
