### ISSUE TITLE
Use default cloud set by default command

### ISSUE THREAD

**Issue by vaglomangirish** [cloudmesh/client#73]
Change implementations of Nova, Key, VM commands to use default cloud set by the 'default' command.

Currently they have been configured to use India cloud by default.

**Comment by gouravshenoy** [comment]
Refactored the Nova & VM commands to use default cloud set by Default command. Previously it was hard-coded to "india". 
No reference of "cloud" found in the KeyCommand, hence did not refactor.

Closing this issue.
