### ISSUE TITLE
command: limits

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#74]
a) limits includes  def set_os_environment(cls, cloudname):

    this methid is clearly useful and i think has been defined elsewhere, there is no need to copy it. Instead your team may want to introduce an "authenticate.py" or "security.py" where you put this method in, Than you make sure that it is called before you call limits and other commands

**Comment by laszewsk** [comment]
Also you may have already implemented this as part of the cloud provider in initialize? so maybe there is nothing to do, but to cleanup the code and make sure that the initialization does what it needs to do. compare the set_os_environment with wht you do in initialize

**Comment by ehdsouza** [comment]
Marking this as invalid as professor has already refactored the code.
