### ISSUE TITLE
command: squeue

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#77]
a) Develop a simple parser class SQUEUE the transfers the contents of the command squeue into a son object

@staticmethod
def squeue_to_json(input_string)

array of 

jobid
partition
name
user
status
time
nodes
nodelist

b) develop elementary find/search

def get(user="gregor")

returns all jobs of the given user

def get(user="gregor", name="experiments")

returns all jobs that have the name experiment a from the user gregor

c) (low priority) develop some graphical representation of the cluster (comet01-??)

show the nodes by status (may be different slurs command) javascript and web browser based

 GUI stuff could be developed later,. we just need simple representation. This is also supposed to be reused by our cloud vms, e.g. use same guy, but put different data into it.

d) future task: develop command line interface, note that Gregor has this done for openpbs, we may be able to leverage after review.

**Comment by gouravshenoy** [comment]
Implemented parser class Squeue, that performs the following:
* transfers the contents of the command squeue into a json object
* elementary find/search
  * ```python
      def get(user="gregor")
  ``` - returns all jobs of the given user
  * ```python
      def get(user="gregor", name="experiments")
  ``` - returns all jobs that have the name experiment a from the user gregor

**Comment by gouravshenoy** [comment]
Closing this issue as Erika has already implemented as part of HPC task.
