### ISSUE TITLE
Keys: get keys from yaml file

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#8]
def get_from_yaml(self, filename):

Note that keys can either point to a filename or be the keys themselves.

This can be auto detected based on prefix, e.g. ssh-rsa ssh-asa, ...

See the original cloudmesh code

**Comment by laszewsk** [comment]
cloudmesh:
   ...
    keys:
        default: name of the key
        keylist:
            keyname: ~/.ssh/id_rsa.pub
            keyname: ssh rsa hajfhjldahlfjhdlsak ..... comment
            github-x: github

**Comment by laszewsk** [comment]
not sure if this is already done

**Comment by vaglomangirish** [comment]
This functionality was already been implemented in the key command with cm key list --source=cloudmesh.
However, this issue helped me in uncovering 2 bugs!

### First:-
If you specify multiple keys, having different paths but same name (id_rsa.pub) in cloudmesh.yaml, the output of the above command would show the last key in the list.

Example:-
Entry in cloudmesh.yaml:-
keys:
    default: null
    keylist:
      keyname: ~/.ssh/id_rsa.pub
      testkey: /home/mangirish/key_expt/id_rsa.pub

$ cm key list --source=cm
{'--all': False,
 '--dir': '~/.ssh',
 '--format': 'table',
 '--git': False,
 '--help': False,
 '--name': None,
 '--select': False,
 '--source': 'cm',
 '--ssh': False,
 '--username': 'none',
 '-f': False,
 '-h': False,
 'FILENAME': None,
 'KEYNAME': None,
 'NAME': None,
 'add': False,
 'default': False,
 'delete': False,
 'get': False,
 'list': True}
KEYNAME = keyname
Name = keyname
KEYNAME = testkey
Name = testkey
+---------+-----------------------------------------------+--------------------------------------------+-------------------------------------------------+--------+
| name    | comment                                       | uri                                        | fingerprint                                     | source |
+---------+-----------------------------------------------+--------------------------------------------+-------------------------------------------------+--------+
| keyname | mangirish@149-160-243-103.dhcp-bl.indiana.edu | file:///home/mangirish/.ssh/id_rsa.pub     | 2d:18:a8:03:1e:e1:7e:fe:b3:fa:59:49:c7:c2:cf:01 | ssh    |
| testkey | mangirish@MangoLap                            | file:///home/mangirish/key_expt/id_rsa.pub | 4e:fc:e8:03:4e:c7:8e:ca:30:1a:54:43:8d:24:90:39 | ssh    |
+---------+-----------------------------------------------+--------------------------------------------+-------------------------------------------------+--------+
info. OK.


Reason is the key name 'rsa' is actually a truncated filename id_rsa.pub with id_ and .pub trimmed off.

### Second:-
If you specify the complete key and not filename, the SSHKey() constructor reported:-
File "/home/mangirish/ENV/lib/python2.7/site-packages/cloudmesh_client/keys/SSHKeyManager.py", line 88, in get_from_yaml
    sshkey = SSHkey()
TypeError: __init__() takes at least 2 arguments (1 given)

__init__() takes at least 2 arguments (1 given)


Delivered fix for both these issues...

**Comment by vaglomangirish** [comment]
Keys in yaml:-
keys:
    default: null
    keylist:
      keyname: ~/.ssh/id_rsa.pub
      testkey: /home/mangirish/key_expt/id_rsa.pub
      ssh-key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzWWw1hY3u2PIQVjE8VvmpN68FFdFZZhkp0VDZyc4a9Ujby73FA5PTE6dZwdGvknjiVX3xBwGhlBzIzvXkHiD2I2EGkR99Y4xOcEZGvZZyA+ktPPiKlfsC9cPH9PBCf6rD84vLeUb57t1Y7dPuH18gRy/ZqzOZPkgk28ZKT0YX2+b8BRjg9lK88ciL4qIoaoOeDjGaXDAa2Y8JAc1AMU4hL/ZXGb3EsiIIsUf9mjjGwnTk44OZghJvmo6e9teBKoZFQdi7WfzPFMUaMui6+KROBrJmep+E2FEBf7UMu4gl5Ib4GNkk+NN5wKS2QYlEvradkwgclzeK5EUsPtnr1wAx keyfortest
  system:


Output of the command:-

$ cm key list --source=cloudmesh
{'--all': False,
 '--dir': '~/.ssh',
 '--format': 'table',
 '--git': False,
 '--help': False,
 '--name': None,
 '--select': False,
 '--source': 'cloudmesh',
 '--ssh': False,
 '--username': 'none',
 '-f': False,
 '-h': False,
 'FILENAME': None,
 'KEYNAME': None,
 'NAME': None,
 'add': False,
 'default': False,
 'delete': False,
 'get': False,
 'list': True}
+---------+-----------------------------------------------+--------------------------------------------------+-------------------------------------------------+--------+
| name    | comment                                       | uri                                              | fingerprint                                     | source |
+---------+-----------------------------------------------+--------------------------------------------------+-------------------------------------------------+--------+
| ssh-key | keyfortest                                    | yaml:///home/mangirish/.cloudmesh/cloudmesh.yaml | 4e:fc:e8:03:4e:c7:8e:ca:30:1a:54:43:8d:24:90:39 |        |
| keyname | mangirish@149-160-243-103.dhcp-bl.indiana.edu | file:///home/mangirish/.ssh/id_rsa.pub           | 2d:18:a8:03:1e:e1:7e:fe:b3:fa:59:49:c7:c2:cf:01 | ssh    |
| testkey | mangirish@MangoLap                            | file:///home/mangirish/key_expt/id_rsa.pub       | 4e:fc:e8:03:4e:c7:8e:ca:30:1a:54:43:8d:24:90:39 | ssh    |
+---------+-----------------------------------------------+--------------------------------------------------+-------------------------------------------------+--------+
info. OK.
