### ISSUE TITLE
Command: Hpc

### ISSUE THREAD

**Issue by ehdsouza** [cloudmesh/client#80]
Implement hpc commands for comet
* [x] squeue
*  [x] sinfo

**Comment by ehdsouza** [comment]
Implemented the following:
cm hpc squeue (this gives the format in json)

To get other formats like table or csv, simply use the --format option
cm hpc squeue --format=table

**Comment by ehdsouza** [comment]
Implemented hpc sinfo for comet...

F:\python_workspace\trial> cm hpc sinfo
{
    "2": {
        "NODELIST": "comet-02-48,comet-12-56,comet-17-39,comet-19-28,comet-20-50,comet-22-21,comet-25-01",
        "PARTITION": "compute*",
        "AVAIL": "up",
        "TIMELIMIT": "2-00:00:00",
        "STATE": "maint*",
        "NODES": "7"
    },
    "3": {
        "NODELIST": "comet-06-45,comet-11-16,comet-13-60,comet-15-[25-28],comet-18-04,comet-26-14",
        "PARTITION": "compute*",
        "AVAIL": "up",
        "TIMELIMIT": "2-00:00:00",
        "STATE": "maint",
        "NODES": "9"
    },
    "4": {
        "NODELIST": "comet-02-62",
        "PARTITION": "compute*",
        "AVAIL": "up",
        "TIMELIMIT": "2-00:00:00",
        "STATE": "drain*",
        "NODES": "1"
    },
    "5": {
......

**Comment by laszewsk** [comment]
makeevery attribute lowercase
