### ISSUE TITLE
Command: Hpc: test

### ISSUE THREAD

**Issue by ehdsouza** [cloudmesh/client#82]
Implement command with the descriptions specified: cm hpc test --cluster=CLUSTER --time=SECONDS

**Comment by ehdsouza** [comment]
Implemented the test command:
C:\Users\erika> cm hpc test --cluster=comet
Warning: Permanently added 'comet.sdsc.xsede.org,198.202.113.253' (RSA) to the list of known hosts.
srun: job 1185345 queued and waiting for resources
srun: job 1185345 has been allocated resources
#CLOUDMESH: Test ok

**Comment by laszewsk** [comment]
what is status

**Comment by ehdsouza** [comment]
This has been completed
