### ISSUE TITLE
Command: Hpc: status

### ISSUE THREAD

**Issue by ehdsouza** [cloudmesh/client#83]
Implement following command:
* [x] cm hpc status
* [x] cm hpc status job=NAME
* [x] nosetest
* [x] documentation

**Comment by ehdsouza** [comment]
Implementation completed...
C:\Users\erika> cm hpc status --job=1154418
{
    "2": {
        "nodelist(reason)": "comet-04-06",
        "name": "NGBW-JOB",

**Comment by laszewsk** [comment]
what is status

**Comment by ehdsouza** [comment]
cm hpc status
cm hpc status job=xx

both have been completed
