### ISSUE TITLE
Command: Hpc: run

### ISSUE THREAD

**Issue by ehdsouza** [cloudmesh/client#85]
* [x] Implement command: cm hpc run SCRIPT
* [x] nosetest
* [x] documentation

**Comment by ehdsouza** [comment]
The command hostname would be submitted..

C:\Users\erika> cm hpc run hostname --p=delta
Enter passphrase for key 'C:\Users\erika\.ssh\id_rsa':
Submitted batch job 140  .The output file erika-2.out is in ~ directory of the cluster

The ouput file is:
C:\Users\erika> ssh india cat erika-2.out
0: #CLOUDMESH: Starting
0: d001
0: #CLOUDMESH: Test ok

**Comment by laszewsk** [comment]
can you make it possible that a user can say both
>  cm hpc run hostname --p=delta
> 
> cm hpc run hostname --queue=delta


Also we need default hpc=hostname

and now i am not sure if we have that, we need for the host a defualt queue

default —hpc=hostname queue=delta

**Comment by ehdsouza** [comment]
Changed partition to queue, and also set the attribute as optional..

C:\Users\erika> cm hpc run uname
ERROR: set default queue using: default queue=<value>
C:\Users\erika> cm default queue=delta
set in defaults queue=delta. ok.
C:\Users\erika> cm hpc run uname
Enter passphrase for key 'C:\Users\erika\.ssh\id_rsa':
Submitted batch job 146  .The output file erika-8.out is in ~ directory of the cluster
C:\Users\erika> ssh india cat erika-8.out
0: #CLOUDMESH: Starting
0: Linux
0: #CLOUDMESH: Test ok

**Comment by laszewsk** [comment]
what is status

**Comment by ehdsouza** [comment]
This would need additional modifications. A rudimentary version is done

**Comment by ehdsouza** [comment]
Added the following:
cm hpc run uname --cluster=india
cm hpc run <script_path>  --cluster=india
