### ISSUE TITLE
admin: remove runtime attachments form github issues

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#86]
* [x] priority urgent
* [x] find attachments
* [x] find way to remove them
* [x] remove them
* [x] make sure they are gone

* [x] make sure this is done for all team members

**Comment by laszewsk** [comment]
I have not found an easy solution yet, simply deleting the comment still makes the attachment still available. Please identify a solution so that they are permanently removed from github.

**Comment by vaglomangirish** [comment]
Awaiting confirmation from the Github support about the removal of the URLs...

**Comment by vaglomangirish** [comment]
Received confirmation from Github team about the removal of attachments.
Verified that they have been removed (Hitting the URLs now returns 404.).
