### ISSUE TITLE
command: hoc

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#88]
hpc queue does not work as it does not capture the case when there is a space in the note or prg listed in the queue

DDD 8 ['1183834', 'compute', 'RUN', 'userxyz', 'R', '19:58:06', '1', 'comet-10-54']
DDD 9 ['1186906', 'compute', 'Word', 'Cou', 'userxyz', 'R', '2:14:28', '4', 'comet-02-59,comet-05-[13,18,26]']

**Comment by laszewsk** [comment]
1186906   compute Word Cou  userxyz  R    2:18:48      4 comet-02-59,comet-05-[13,18,26]

**Comment by ehdsouza** [comment]
Hpc queue works now.
