### ISSUE TITLE
First real bugs: Inconsistent VM, Default, Image, Flavor classes

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#92]
I recoomend that we introduce a ResourceObject class that is somewhat defined as follows,(pseudocode):

  class ResourceObject

     def list (cloud=None, user=None, project=None, fomrat="json")

     def get(**kwargs) 
           
            samples: cloud=, user=, project=,
            there may be more 
           
     def attributes():
           returns the attributes that are contained in a database object, we assume object is flat

     def delete (same parameters as list) and is assumed

     def clear (same parameters as list)   and is assumed

     def delete (on object ids, after a find)

     def delete (on object after a find)

     type of arg is used to distingish behavior of delete

**Comment by gouravshenoy** [comment]
A ListResource class has been implemented, and all the vm.py, default.py, image.py & flavor.py are extending this resource class.
