### ISSUE TITLE
command: quata list

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#98]
cm quota list
Error in setting OS environment, string indices must be integers, not str

**Comment by ehdsouza** [comment]
Also, refactored code to use the new provider..

cm quota list
+-----------------------------+-------+
| Quota                       | Limit |
+-----------------------------+-------+
| fixed_ips                   | -1    |
| injected_files              | 5     |
| server_group_members        | 10    |
| server_groups               | 10    |
| floating_ips                | 10    |
| instances                   | 10    |
| security_groups             | 10    |
| security_group_rules        | 20    |
| cores                       | 20    |
| key_pairs                   | 100   |
| metadata_items              | 128   |
| injected_file_path_bytes    | 255   |
| injected_file_content_bytes | 10240 |
| ram                         | 51200 |
+-----------------------------+-------+
